### ISSUE TITLE
[docs] Review updated example walkthrough

### ISSUE THREAD

**Issue by zhao-cy** [PennLINC/babs#107]
In example walkthrough, after Sydney's first round of review, there are several things added by me (instead of directly using words suggested by Sydney), so it will be great to have another quick round of review:

- [ ] YAML file, section `cluster_resources`:
  - [ ] For Slurm clusters: how to add partitions request
  - [ ] For CUBIC: how to avoid those compute nodes 
  - [ ] "If needed, you may add more requests for other resources, e.g., runtime limit of 20min, Or even resources without pre-defined keys from BABS. See [Section cluster_resources](https://github.com/PennLINC/babs/issues/preparation_config_yaml_file.html#cluster-resources) for how to do so."
- [ ] Singularity (itself) version - after Dorota replicates example walkthru (PR #109)
- [ ] After removing `temporary_disk_space: 20G` from the example YAML file - after Dorota replicates example walkthru (PR #109)
- [ ] The expected generated directives - see PR #109
- [ ] what else?

**Comment by mattcieslak** [comment]
Going to redo the walkthrough with simbids
