### ISSUE TITLE
[DOCS] NMIND checklist - targets before paper submission

### ISSUE THREAD

**Issue by zhao-cy** [PennLINC/babs#110]
Domain Documentation:
- [ ] (silver) Background/significance of program
- [ ] (silver) Any alternative usage that is advertised is thoroughly documented
- [ ] (silver) A statement of supported operating systems / environments (i.e., could be a container recipe)
- [ ] (gold) Continuous integration badges in README for build status
- [ ] (gold) Continuous integration badges in README for coverage
- [ ] (gold) Maintenance status is documented (e.g., expected turnaround time on pull requests, whether project is maintained)

Domain Infrastructure:
- [ ] (bronze) Digital Object Identifier (DOI) points to latest version (e.g., Zenodo)
- [ ] (silver) Issue template(s) available (i.e., information requested by developers)
- [ ] (silver) No excessive files included (i.e., unused files / cache; e.g., .gitignore)

Domain Testing:
- [ ] (bronze) Provide instructions for users to run tests that include instructions for evaluation for correct behavior
- [ ] Testing coverage > ?
