### ISSUE TITLE
[DOCS] NMIND checklist: on roadmap

### ISSUE THREAD

**Issue by zhao-cy** [PennLINC/babs#111]
Domain Documentation:
- [ ] (gold) Has a documented style guide

Domain Infrastructure:
- [ ] (gold) Continuous integration validates style
- [ ] (gold) Journal of Open Source Software submission
- [ ] (gold) Code of Conduct present

Domain Testing:
- [ ] Testing coverage > ?
- [ ] Benchmarking information is provided for examples
