### ISSUE TITLE
[DOCS] ask Taylor to review new NMIND check achievements

### ISSUE THREAD

**Issue by zhao-cy** [PennLINC/babs#152]
This is to ask Taylor to review recent changes in BABS (mostly in docs) and to make sure more NMIND checks have been achieved.

**Comment by zhao-cy** [comment]
These NMIND checks have been achieved:

Documentation Domain:
- [ ] issue #149  - see PR #148
- [ ] issue #150 - see PR #148
- [ ] issue #151 - see PR #148
--> so all checks at Silver level in this domain are done.

Infrastructure Domain:
- [ ] issue #147 - see PR #130 
- [ ] (silver) No excessive files included (i.e., unused files / cache; e.g., .gitignore)
    * I have cleaned up files on github, esp `notebooks` folder 
--> so all checks at Silver level in this domain are done.

**Comment by zhao-cy** [comment]
(def not a Friday afternoon work - I will ask you on Monday, Taylor!)

**Comment by zhao-cy** [comment]
Confirmed by Taylor today (10/30/2023) that all silver checks have been done except testing.
